### ISSUE TITLE
heal for vrp server

### ISSUE THREAD

**Issue by xxxdxd719** [Joeyarrabi/skidmenu#4]
plz make a heal pack for the vrp server

**Comment by o305** [comment]
If you actually use the menu, you will see we added "Heal option"

**Comment by xKirtle** [comment]
In order to recover your hp (Health) in GtaV you can use the Natives. There's no specific Heal command for ESX and for VRP, there's just a global way to do it. I believe there's a way to heal a player on the Specific Player Menu under the All Players Menu but I'll add it to the Self Menu for easier access. Anyway, it's as easy as `SetEntityHealth(PlayerPedId(), 200)`
